package com.uguraltintas.periodictable

object Elements {
    fun getElementData(): ArrayList<Element> {
        val elementList = arrayListOf<Element>()
        // Period 1
        elementList.add(Element("Hydrogen", "H", 1, 1, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Helium", "He", 2, 1, "", backgroundColor = "#FFE3B8"))
        // Period 2
        elementList.add(Element("Lithium", "Li", 3, 2, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Beryllium", "Be", 4, 2, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Boron", "B", 5, 2, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Carbon", "C", 6, 2, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Nitrogen", "N", 7, 2, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Oxygen", "O", 8, 2, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Fluorine", "F", 9, 2, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Neon", "H", 10, 2, "", backgroundColor = "#FFE3B8"))
        // Period 3
        elementList.add(Element("Sodium", "Na", 11, 3, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Magnesium", "Mg", 12, 3, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Aluminium", "Al", 13, 3, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Silicon", "Si", 14, 3, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Phosphorus", "P", 15, 3, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Sulfur", "S", 16, 3, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Chlorine", "Cl", 17, 3, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Argon", "Ar", 18, 3, "", backgroundColor = "#FFE3B8"))
        // Period 4
        elementList.add(Element("Potassium", "K", 19, 4, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Calcium", "Ca", 20, 4, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("Scandium", "Sc", 21, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Titanium", "Ti", 22, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Vanadium", "V", 23, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Chromium", "Cr", 24, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Manganese", "Mn", 25, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Iron", "Fe", 26, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Cobalt", "Co", 27, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Nickel", "Ni", 28, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Copper", "Cu", 29, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Zinc", "Zn", 30, 4, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Gallium", "Ga", 31, 4, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Germanium", "Ge", 32, 4, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Arsenic", "As", 33, 4, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Selenium", "Se", 34, 4, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Bromine", "Br", 35, 4, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Krypton", "Kr", 36, 4, "", backgroundColor = "#FFE3B8"))
        // Period 5
        elementList.add(Element("Rubidium", "Rb", 37, 5, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Strontium", "Sr", 38, 5, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("Yttrium", "Y", 39, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Zirconium", "Zr", 40, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Niobium", "Nb", 41, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Molybdenum", "Mo", 42, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Technetium", "Tc", 43, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Ruthenium", "Ru", 44, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Rhodium", "Rh", 45, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Palladium", "Pd", 46, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Silver", "Ag", 47, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Cadmium", "Cd", 48, 5, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Indium", "In", 49, 5, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Tin", "Sn", 50, 5, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Antimony", "Sb", 51, 5, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Tellurium", "Te", 52, 5, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Iodine", "I", 53, 5, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Xenon", "Xe", 54, 5, "", backgroundColor = "#FFE3B8"))
        // Period 6
        elementList.add(Element("Cesium", "Cs", 55, 6, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Barium", "Ba", 56, 6, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("", "", 57, 6, "", true, backgroundColor = "#A9FFFF"))
        elementList.add(Element("Hafnium", "Hf", 72, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Tantalum", "Ta", 73, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Tungsten", "W", 74, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Rhenium", "Re", 75, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Osmium", "Os", 76, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Iridium", "Ir", 77, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Platinum", "Pt", 78, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Gold", "Au", 79, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Mercury", "Hg", 80, 6, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Thallium", "Tl", 81, 6, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Lead", "Pb", 82, 6, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Bismuth", "Bi", 83, 6, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Polonium", "Po", 84, 6, "", backgroundColor = "#DEECB5"))
        elementList.add(Element("Astatine", "At", 85, 6, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Radon", "Rn", 86, 6, "", backgroundColor = "#FFE3B8"))
        // Period 7
        elementList.add(Element("Francium", "Fr", 87, 7, "", backgroundColor = "#FFC0C0"))
        elementList.add(Element("Radium", "Ra", 88, 7, "", backgroundColor = "#D2D2FF"))
        elementList.add(Element("", "", 89, 7, "", true, backgroundColor = "#BDFFE9"))
        elementList.add(Element("Rutherfordium", "Rf", 104, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Dubnium", "Db", 105, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Seaborgium", "Sg", 106, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Bohrium", "Bh", 107, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Hassium", "Hs", 108, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Meitnerium", "Mt", 109, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Darmstadtium", "Ds", 110, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Roentgenium", "Rg", 111, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Copernicium", "Cn", 112, 7, "", backgroundColor = "#B9DCFF"))
        elementList.add(Element("Nihonium", "Nh", 113, 7, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Flerovium", "Fl", 114, 7, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Moscovium", "Mc", 115, 7, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Livermorium", "Lv", 116, 7, "", backgroundColor = "#B9FFB9"))
        elementList.add(Element("Tennessine", "Ts", 117, 7, "", backgroundColor = "#FFFFB5"))
        elementList.add(Element("Oganesson", "Og", 118, 7, "", backgroundColor = "#FFE3B8"))

        // Period 6 57..71
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Lanthanum", "La", 57, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Cerium", "Ce", 58, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Praseodymium", "Pr", 59, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Neodymium", "Nd", 60, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Promethium", "Pm", 61, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Samarium", "Sm", 62, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Europium", "Eu", 63, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Gadolinium", "Gd", 64, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Terbium", "Tb", 65, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Dysprosium", "Dy", 66, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Holmium", "Ho", 67, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Erbium", "Er", 68, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Thulium", "Tm", 69, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Ytterbium", "Yb", 70, 6, "", backgroundColor = "#A9FFFF"))
        elementList.add(Element("Lutetium", "Lu", 71, 6, "", backgroundColor = "#A9FFFF"))

        // Period 7 89..103
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Blank", "B", 1, 1, "", false))
        elementList.add(Element("Actinium", "Ac", 89, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Thorium", "Th", 90, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Protactinium", "Pa", 91, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Uranium", "U", 92, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Neptunium", "Np", 93, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Plutonium", "Pu", 94, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Americium", "Am", 95, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Curium", "Cm", 96, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Berkelium", "Bk", 97, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Californium", "Cf", 98, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Einsteinium", "Es", 99, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Fermium", "Fm", 100, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Mendelevium", "Md", 101, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Nobelium", "No", 102, 7, "", backgroundColor = "#BDFFE9"))
        elementList.add(Element("Lawrencium", "Lr", 103, 7, "", backgroundColor = "#BDFFE9"))


        return elementList

    }
}